### ISSUE TITLE
File 'Data\Haarcascade\haarcascade_frontalface_alt.xml' not found

### ISSUE THREAD

**Issue by gouteru** [Fictiverse/Redream#19]
Please help I got an error below

```
System.IO.FileNotFoundException: File 'Data\Haarcascade\haarcascade_frontalface_alt.xml' not found
   at Emgu.CV.CascadeClassifier..ctor(String fileName)
   at Redream.MyFunctions.DetectAndApplyMask(Bitmap img) in S:\Users\ideo\Documents\Code\Redream\Redream\MyFunctions.cs:line 255
   at Redream.FormScreenShot.TakeScreeenShot() in S:\Users\ideo\Documents\Code\Redream\Redream\FormScreenShot.cs:line 219
   at Redream.Form1.buttonStart_Click(Object sender, EventArgs e) in S:\Users\ideo\Documents\Code\Redream\Redream\Form1.cs:line 240
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

I have set up with the followings.

- webui v1.6.0
- dotnet-sdk-6.0.413-win-x64.exe
- latest controlnet 

When click the play button of Redream, the error above happend and no output.

**Comment by jynrock** [comment]
Hi
I have the same issue
Anyone have an idea to solve it please ?
